# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelRecorder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelRecorder
pod 'RealmSwift', '~> 2.4'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'

pod 'CVCalendar', '~> 1.4'
end
